# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET http://127.0.0.1:8000/api/sensors/
Content-Type: application/json

###

# создание датчика
POST http://127.0.0.1:8000/api/sensors/
Content-Type: application/json

{ 
  "title": "sensor for kitchen 2",
  "description": "text"
}

###

# обновление датчика
PATCH http://127.0.0.1:8000/api/sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor_id": "1",
  "temperature": "22"
}

###

# получение информации по датчику
GET http://localhost:8000/api/sensors/1/
Content-Type: application/json
